# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moment',
            options={},
        ),
        migrations.AlterField(
            model_name='quantity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
