# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_models', '0003_auto_20160530_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='ingredients',
            field=models.ManyToManyField(related_name='quantities', through='recipes_models.Quantity', to='recipes_models.Ingredient'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='moment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='recipes_models.Recipe'),
        ),
    ]
