# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_models', '0004_auto_20160530_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='extra_ingredients',
            field=models.ManyToManyField(to='recipes_models.Ingredient'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quantity',
            name='comment',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
