# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_models', '0007_auto_20160531_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name_plural': 'recipes'},
        ),
    ]
