# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_models', '0008_auto_20160531_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
