# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_models', '0010_auto_20160531_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='extra_ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='recipes_models.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
