# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_models', '0012_auto_20160531_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
